### ISSUE TITLE
Use 'with' to open file in validation.py

### ISSUE THREAD

**Issue by guidovranken** [TAXIIProject/libtaxii#167]
https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/validation.py#L158

I would like to propose to change this:

```python
f = open(file_location, 'r')
etree_xml = parse(f)
f.close()
```

into this:

```python
with open(file_location, 'r') as f:
    etree_xml = parse(f)
```

To ensure that if the ```parse()``` call fails, for whatever reason, for example due to the XML file being parsed containing a "billion laughs attack", then the file pointer is automatically transitioned to a closed state.
Not closing used file pointers while continuing to open new ones (feasible scenario for some use cases of libtaxii) may lead to hitting the maximum open files limit imposed by the operating system.

You can test this by trying to open the following XML file (taken from https://en.wikipedia.org/wiki/Billion_laughs#Code_example )

```xml
<?xml version="1.0"?>
<!DOCTYPE lolz [
 <!ENTITY lol "lol">
 <!ELEMENT lolz (#PCDATA)>
 <!ENTITY lol1 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
 <!ENTITY lol2 "&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;&lol1;">
 <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
 <!ENTITY lol4 "&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;&lol3;">
 <!ENTITY lol5 "&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;&lol4;">
 <!ENTITY lol6 "&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;&lol5;">
 <!ENTITY lol7 "&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;&lol6;">
 <!ENTITY lol8 "&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;&lol7;">
 <!ENTITY lol9 "&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;&lol8;">
]>
<lolz>&lol9;</lolz>
```

With the current code, the ```f``` variable will maintain its open state after a ```lxml.etree``` raises an exception whereas my code enforces automatic closure.

**Comment by gtback** [comment]
Thanks, @guidovranken. I replaced all the instances of `open` that didn't use a context manager, including in several scripts.
