### ISSUE TITLE
Version in trunk should be different from release version

### ISSUE THREAD

**Issue by traut** [TAXIIProject/libtaxii#180]
Current trunk is already different from `1.1.105` release but still marked as one (https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/__init__.py#L12). This is confusing for users who install libtaxii directly from github repo. 

As far as I know, the version of the codebase in trunk should be different from last release and should be marked as "alpha". In this case, it can be `1.1.106a`

**Comment by MarkDavidson** [comment]
:+1: 

I also received an offline request for a release of libtaxii, which I'll be looking into today.

-Mark
