### ISSUE TITLE
libtaxii.common.get_xml_parser() comments don't align with return value

### ISSUE THREAD

**Issue by bworrell** [TAXIIProject/libtaxii#183]
https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/common.py#L57

The comment says that a parser with `huge_tree=True` will be returned if one hasn't already been set, though the returned parser sets `huge_tree=False` by default.

**Comment by MarkDavidson** [comment]
The comment is wrong, not the code.

This was the result of some fixing we did to address XML parsing vulnerabilities and the comment never got updated.

-Mark

**Comment by gtback** [comment]
Fixed by #208
