### ISSUE TITLE
Add support for STIX 1.2

### ISSUE THREAD

**Issue by MarkDavidson** [TAXIIProject/libtaxii#192]
Off the top of my head, this includes:
- Add a Content Binding ID for STIX 1.2. `urn:stix.mitre.org:xml:1.2`

I'm not sure if there's anything else. Whoever implements this change should look through how current Content Binding IDs are used and see if there's any other necessary changes.

-Mark

**Comment by brlogan** [comment]
Do you guys intend to add a content binding for STIX 1.2? Seems long overdue.

**Comment by gtback** [comment]
Yeah, we should probably do this 😉 . I didn't realize we didn't already support STIX 1.2 😮

**Comment by brlogan** [comment]
Thanks!!
