### ISSUE TITLE
Python 2.7.3 doesn't have ssl._create_default_https_context

### ISSUE THREAD

**Issue by MarkDavidson** [TAXIIProject/libtaxii#203]
From @brlogan [1]

> Oh, I almost forgot! I ran into another issue when testing your change. The version of Python I was running 2.7.3 doesn't have `ssl._create_default_https_context`:
https://github.com/TAXIIProject/libtaxii/blob/master/libtaxii/clients.py#L422

> After a little research, it looks like that may have been added in 2.7.9, but don't quote me on that. You may have to account for the micro version in your first if statement. Something like:
```python
if ((sys.version_info.major == 2 and sys.version_info.minor == 6) or
    (sys.version_info.major == 2 and sys.version_info.minor == 7 and sys.version_info.micro < 9)):
```

[1] https://github.com/TAXIIProject/libtaxii/issues/200#issuecomment-146426057

**Comment by MarkDavidson** [comment]
@traut Could you take a look at this one?

**Comment by traut** [comment]
@MarkDavidson @brlogan as `context` property that libtaxii uses [has been added](https://docs.python.org/2.7/library/httplib.html?highlight=httpsconnection#httplib.HTTPSConnection) only in `2.7.9` and `2.7.10` is official latest `2.7` version, the only and recommended solution is to upgrade to `2.7.10`

**Comment by brlogan** [comment]
Based on your code, it seems you support Python 2.6, and 2.6 also does not have the `context` property, right? So why not have 2.7.x versions less than 2.7.9 fall back to the code intended for Python 2.6? I am currently doing that using the fix i suggested above, and I haven't noticed any issues. If it doesn't break anything else, it would be a simple change, and add a lot more compatibility.

At the very least, some sort of error message indicating this is a python version issue would be much more helpful than the current error.

**Comment by traut** [comment]
@brlogan good point, there definitely should be a proper error message

**Comment by ScottyAU** [comment]
This one just caught us after moving to 1.1.108 (or trying too).

I'd not that Ubuntu 14 is sticking with 2.7.6 which most of our partners are running atm server wise.

**Comment by traut** [comment]
Fixed in pull request https://github.com/TAXIIProject/libtaxii/pull/204

Please verify and merge

**Comment by MarkDavidson** [comment]
I just merged into master. @traut, thank you for fixing my Python 2 tunnel vision.

@ScottyAU, @brlogan, can you confirm the fix? If this is hitting a production issue for you I can issue a release as soon as you confirm.

Thank you.
-Mark

**Comment by ScottyAU** [comment]
@MarkDavidson works like a charm mate.  If you release let me know - and I'll give that  whirl too.

Thanks for the quick turn around!

**Comment by gtback** [comment]
Can this get closed?

**Comment by ScottyAU** [comment]
@gtback @MarkDavidson did the fix get rolled into a release yet?  We've got our requirements.txt specifying the previous release until it does.

**Comment by MarkDavidson** [comment]
I haven't had time to push a release yet, but it's on my to-do list. My apologies for the delay, I should be able to get to it early next week.

**Comment by MarkDavidson** [comment]
https://pypi.python.org/pypi/libtaxii/1.1.109

**Comment by brlogan** [comment]
This works much better! Thanks for the fix!
