### ISSUE TITLE
inbox_client: default Destination_Collection_Name

### ISSUE THREAD

**Issue by clenk** [TAXIIProject/libtaxii#209]
The [Getting Started](http://yeti.readthedocs.io/en/latest/getting_started.html) page of Yeti says that 

> Out of the box, inbox_client sets the Destination_Collection_Name parameter of the Inbox Message to default and sends a default STIX XML document.

However, this is not true; it sets Destination_Collection_Name to `None`. It should be set to `default` as in the documentation.

**Comment by gtback** [comment]
`Destination_Collection_Name` is not a required field on Inbox Messages, so this is not something we should do in libtaxii.

The YETI documentation should be updated to explain that you can use the `--dcn` argument to `inbox_client`.
