### ISSUE TITLE
How to set timeout in func call_taxii_service2?

### ISSUE THREAD

**Issue by Jie-Yang** [TAXIIProject/libtaxii#214]
Hi,

I am wondering whether there is a way to set timeout when call function call_taxii_service2?

in urllib.request.urlopen(req) which is called by call_taxii_service2, I can set timeout parameter as urllib.request.urlopen(req,timeout=10). But I donot want to change libtaxii source code to achieve this. I am wondering is there anyway to set this parameter in libtaxii without changing source code?

Thanks for any suggestions.

**Comment by gtback** [comment]
There's not a way to do this currently without modifying libtaxii source. If you'd like, we can add a `timeout` parameter to `call_taxii_service2`, which we just pass through to `urlopen`. Would that help?

**Comment by Jie-Yang** [comment]
@gtback Thank you so much for the help. If you could add timeout to the call_taxii_service2, this is really helpful. 

Just one more question, after you change your source code, can I get the latest version by using pip install?

**Comment by gtback** [comment]
After we change the code, we will need to release a new version before it will be available with pip (unless you use pip to install directly from GitHub, which is not recommended, but can be an okay short-term workaround). 

We released the last version a couple months ago, so we could release a new version shortly. I prefer not to release a new version for each change, but given that the pace of new features and bug reports has slowed down dramatically, releasing 1.1.111 soon is certainly feasible.

Are there other parameters to `urlopen` that would be good to pass through?

**Comment by Jie-Yang** [comment]
Hi @gtback ,

I have double checked the urlopen api, and timeout seems like the only special parameter. So I would say adding timeout to the api is good enough.

Thanks again for the help.

**Comment by gtback** [comment]
Fixed by #220
