### ISSUE TITLE
message_11.py: Unicode strings with encoding declaration are not supported. 

### ISSUE THREAD

**Issue by CQRuu** [TAXIIProject/libtaxii#219]
Hi there! 

For some reasons I received such an error when I try to poll from my TAXII Server. How can I resolve this issue / find a workaround? (this error happens regardless of whether my TAXII Server has any content (xml files) or not)

`File \"/usr/local/lib/python3.4/dist-packages/libtaxii/messages_11.py\", line 80, in get_message_from_xml\n    etree_xml = parse_xml_string(decoded_string)\n  File \"/usr/local/lib/python3.4/dist-packages/libtaxii/common.py\", line 54, in parse_xml_string\n    return parse(xmlstr)\n  File \"/usr/local/lib/python3.4/dist-packages/libtaxii/common.py\", line 36, in parse\n    e = etree.parse(s, get_xml_parser()).getroot()\n  File \"src/lxml/lxml.etree.pyx\", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:79841)\n  File \"src/lxml/parser.pxi\", line 1810, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:116399)\n  File \"src/lxml/parser.pxi\", line 1825, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116615)\nValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.", "level": "error", "logger": "opentaxii.middleware", `

**Comment by gtback** [comment]
Hi, @CQRuu, can you add a copy of XML that causes this error? If it's too big, feel free to send it to `gback [at] mitre.org`.

**Comment by gtback** [comment]
Thanks for sending a detailed description via email, @CQRuu.

I was able to reproduce the error with the following code (on Python 3.6):

```python
from libtaxii.messages_11 import get_message_from_xml

discovery_request_with_encoding = b"""<?xml version="1.0" encoding="UTF-8" ?>
<taxii_11:Discovery_Request xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1"
    xsi:schemaLocation="http://taxii.mitre.org/messages/taxii_xml_binding-1.1 http://taxii.mitre.org/messages/taxii_xml_binding-1.1"
    message_id="145d1888-f5c8-5c9a-bee2-d0f99081283b" />
"""

get_message_from_xml(discovery_request_with_encoding)
```

I could also get a similar error in Python 2 (without the `b` prefix on strings)

It seems like we are inconsistently using Unicode and byte strings or converting between them improperly. It will take a bit of work to go through the library and figure out the correct place to do this.

**Comment by alatif113** [comment]
Ran into a similar problem. Is there a timeline for a fix for this?

**Comment by gtback** [comment]
@CQRuu , @alatif113 : Sorry this took so long to fix. 

I'd like to make a new release of libtaxii with this fix, but can you test to confirm the current master branch is working for you first?

**Comment by alatif113** [comment]
@gtback Not getting the error anymore with the master branch. Thanks!

**Comment by CQRuu** [comment]
@gtback thank you! it works for me too. :+1:

**Comment by traut** [comment]
same issue for XML content blocks with specified encoding

**Comment by gtback** [comment]
Thanks, @traut . I'm not surprised this error happened somewhere else.
