### ISSUE TITLE
clients.py httpsConnection Python version check error

### ISSUE THREAD

**Issue by melegar** [TAXIIProject/libtaxii#224]
in the __init__ function for VerifiableHTTPSConnection in clients.py the first step is to do a python version check.  However, the script only looks for python 2.6, 2.7 or 3.4.  If someone is running Python version 3.5 or 3.6 the script will fail with the Unsupported Python version error.

**Comment by gtback** [comment]
Link to relevant code: https://github.com/TAXIIProject/libtaxii/blob/a865deaca55112eef2ab7fe50ba088a42bd95c16/libtaxii/clients.py#L430-L431

Also related to #222 (in that we should probably fix them both at the same time).

**Comment by gtback** [comment]
Thanks, @melegar
