### ISSUE TITLE
Python3 bugs when running poll_client

### ISSUE THREAD

**Issue by kralca** [TAXIIProject/libtaxii#227]
Hi, I discovered a couple of issues when running poll_client with Python3:

* str.translate method only takes one parameter in Python 3 (see `gen_filename` method in `libtaxii/common.py`)
* files need to be opened with 'wb' in the `write_cbs_from_poll_response_*` methods in `libtaxii/scripts/__init__.py`

**Comment by gtback** [comment]
Thanks, @kralca. 

The first issues should be pretty straightforward to fix (though we're using `str.translate` mostly to delete unwanted characters). 

For the second one, what is the actual problem that's occurring? Is the newline translation of the default `t` mode causing problems? I want to make sure it's not causing similar problems elsewhere in the code.

I'd rather treat these as separate issues, so if you can explain the second one better, I'll move it to its own issue.

**Comment by kralca** [comment]
Hi @gtback, regarding the second issue, I'm not exactly certain of the cause. I suspect though it has something to do with the explanation here: https://docs.python.org/3/howto/pyporting.html#text-versus-binary-data

In particular, this bit:

> As part of this dichotomy you also need to be careful about opening files. Unless you have been working on Windows, there is a chance you have not always bothered to add the b mode when opening a binary file (e.g., rb for binary reading). Under Python 3, binary files and text files are clearly distinct and mutually incompatible; see the io module for details. Therefore, you must make a decision of whether a file will be used for binary access (allowing binary data to be read and/or written) or textual access (allowing text data to be read and/or written). You should also use io.open() for opening files instead of the built-in open() function as the io module is consistent from Python 2 to 3 while the built-in open() function is not (in Python 3 it’s actually io.open()). Do not bother with the outdated practice of using codecs.open() as that’s only necessary for keeping compatibility with Python 2.5.

Here's the exception that's thrown:

```
$ poll_client --collection guest.Abuse_ch --begin-timestamp 2017-08-03T00:00:00+00:00  > /dev/null
Traceback (most recent call last):
  File "/Users/bruce/venvs/libtaxii3/lib/python3.5/site-packages/libtaxii-1.1.111-py3.5.egg/libtaxii/scripts/__init__.py", line 379, in __call__
    self.handle_response(r, args)
  File "/Users/bruce/venvs/libtaxii3/lib/python3.5/site-packages/libtaxii-1.1.111-py3.5.egg/libtaxii/scripts/poll_client.py", line 87, in handle_response
    self.write_cbs_from_poll_response_11(response, dest_dir=args.dest_dir, write_type_=args.write_type)
  File "/Users/bruce/venvs/libtaxii3/lib/python3.5/site-packages/libtaxii-1.1.111-py3.5.egg/libtaxii/scripts/__init__.py", line 311, in write_cbs_from_poll_response_11
    f.write(cb.content)
TypeError: write() argument must be str, not bytes
```

I tried suggestion from the above site of using `io.open` instead of `open` but this did not fix the problem. This seems to suggest that perhaps the open call should be 'wb' for both Python2 and Python3.

**Comment by kralca** [comment]
Also, the `libtaxii.messages_11.ContentBlock.content` property setter calls `libtaxii.common.stringify_content` which is potentially returning bytes rather than a str.
