### ISSUE TITLE
Python3 'HTTPMessage ' object has no attribute 'getheader'

### ISSUE THREAD

**Issue by Bart-o-zz** [TAXIIProject/libtaxii#228]
With Python3, when receiving an error message from a TAXII server, Python3 raises error : 'HTTPMessage ' object has no attribute 'getheader'

This errir messages is caused because getheader() should be get() when using Python3

for example: 
libtaxii/__init__.py line 54 and 55

```python
def get_message_from_urllib2_httperror(http_response, in_response_to):
    """ This function should not be called by libtaxii users directly. """
    taxii_content_type = http_response.info().get('X-TAXII-Content-Type')
    _, params = cgi.parse_header(http_response.info().get('Content-Type'))
    encoding = params.get('charset', 'utf-8')
    response_message = http_response.read()
```

**Comment by gtback** [comment]
Thanks for opening this, @Bart-o and sorry for not seeing it right away. I'll hopefully have a chance to look at it soon.
