### ISSUE TITLE
ValueError: Unsupported namespace: http://taxii.mitre.org/messages/taxii_xml_binding-1.1

### ISSUE THREAD

**Issue by AjayS91** [TAXIIProject/libtaxii#229]
get_message_from_requests_http_response
    return tm10.get_message_from_xml(response_message, encoding)
  File "/home/ubuntu/ctix-2/venv/lib/python3.5/site-packages/libtaxii/messages_10.py", line 76, in get_message_from_xml
    raise ValueError('Unsupported namespace: %s' % qn.namespace)
ValueError: Unsupported namespace: http://taxii.mitre.org/messages/taxii_xml_binding-1.1

**Comment by gtback** [comment]
Thanks for the report, @AjayS91 !

Looks like a message with the TAXII 1.1 binding is being parsed by the parser for TAXII 1.0 (messages_10.py). It's possible there's some conflicting information in the message itself, or the server is returning an invalid message, or there is a bug in libtaxii, but without more information I can't say for sure.

**Comment by gtback** [comment]
@AjayS91 do you have any more information on this? It is indeed true that `http://taxii.mitre.org/messages/taxii_xml_binding-1.1` is not a supported namespace in the context of messages_10.py. Without more information, I can't tell if this is a bug in libtaxii or not.

**Comment by AjayS91** [comment]
@gtback  I think there is the error in XML data.
My apologies for late reply.

**Comment by gtback** [comment]
No worries. Thanks for letting us know. I'm going to close this, but if you see the problem again or if there's anything we need to fix/change in libtaxii, feel free to reopen!
