### ISSUE TITLE
Security risk on passing password as command-line arg to poll_client

### ISSUE THREAD

**Issue by dwilches** [TAXIIProject/libtaxii#234]
According to the [poll_client docs](https://libtaxii.readthedocs.io/en/stable/scripts.html), the only way to pass the password used for authentication is through a command-line argument. But that implies a security risk: any user logged into the system can use `ps` or `/proc` to find out the parameters passed to `poll_client` like so:

```
dwilches $ bin/poll_client --username hello --pass PASSWORD --key ... --cert ... -u ...
dwilches $ ps -fea | grep poll_client
dwilches.+ 18395 18394  0 22:29 pts/0    00:00:00 bin/poll_client --username hello --pass PASSWORD --key ... --cert ... -u ...
```

Which means, the users will see the password in clear text. This is, even users that don't have `sudo` privileges. This also means logging software that takes snapshots of current running processes will keep copies of the clear-text passwords in their databases or log-files.

Could you provide a `pass_file` where we can pass a file that contains the password? We can secure that file to be only readable by the user that executes `poll_client`.

**Comment by emmanvg** [comment]
@dwilches, I have extended your idea to store much more than the password inside the configuration file. Feel free to look at the PR, but these changes should be available in the next release.

**Comment by dwilches** [comment]
Thanks! That's great.
