### ISSUE TITLE
Release source distribution to PyPI

### ISSUE THREAD

**Issue by sunpoet** [TAXIIProject/libtaxii#241]
Could you please provide the source distribution on PyPI?
Thanks.

**Comment by emmanvg** [comment]
Hi @sunpoet the release is was up on PyPI (https://pypi.org/project/libtaxii/#history) on the same day. Let me know if you encounter any problems. You can try the command below:

```
pip install --upgrade libtaxii
```

**Comment by emmanvg** [comment]
I misinterpreted your issue @sunpoet, I added the source on PyPI (https://pypi.org/project/libtaxii/#files)

**Comment by sunpoet** [comment]
That's great. Thanks!
