### ISSUE TITLE
Server verification does not happen on Python 2.7.9+

### ISSUE THREAD

**Issue by nschwane** [TAXIIProject/libtaxii#242]
Server verification does not happen on Python 2.7.9+ and Python 3+. The issue relates to using `ssl.Purpose.CLIENT_AUTH` at https://github.com/TAXIIProject/libtaxii/blob/1.1.116/libtaxii/clients.py#L431. That turns off verification in the context. The context purpose should be `ssl.Purpose.SERVER_AUTH` if `verify_server is True`.

```
>>> import ssl
>>> ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
>>> ctx.check_hostname
False
>>> ctx.verify_mode
<VerifyMode.CERT_NONE: 0>
>>> 
>>> ctx = ssl.create_default_context(ssl.Purpose.SERVER_AUTH)
>>> ctx.check_hostname
True
>>> ctx.verify_mode
<VerifyMode.CERT_REQUIRED: 2>
```

**Comment by motok** [comment]
Hi,
I also observed the verification of server certs not happened, in my case via command 
line utilities such as /usr/local/bin/discovery_client.
I made a quick-hack at https://github.com/motok/libtaxii/tree/ssl_verify_server 
and eager to hear comments.

Thank you.
mk

**Comment by nschwane** [comment]
@motok I think these lines of yours are redundant if the purpose is initially set to `SERVER_AUTH`:
```
self.context.load_verify_locations(cafile=ca_certs)
self.context.check_hostname = True
self.context.verify_mode = ssl.CERT_REQUIRED
```
In addition, you only want to turn verification on if `verify_server == True`. Something like the following might be all that is necessary:
```
self.context = ssl.create_default_context(
    ssl.Purpose.SERVER_AUTH if verify_server else ssl.Purpose.CLIENT_AUTH,
    cafile=ca_certs
)
```

**Comment by motok** [comment]
@nschwane Thank you very much for your comments.
I just thought setting Purpose.CLIENT_AUTH is for verifying client certs at server side, which is required in my use case.
But CLIENT_AUTH is not for the client side, so I can read from the manual (https://docs.python.org/3/library/ssl.html#constants).
If so, we should set SERVER_AUTH instead, as you've mentioned in your first message.
Thank you very much, I will update my patch later!

**Comment by emmanvg** [comment]
It seems both of you (@motok @nschwane) are very close to having a solution. I would be fine with a PR that addresses the problem.
