### ISSUE TITLE
Unicode SerialisationError occurs for valid XML

### ISSUE THREAD

**Issue by advptr** [TAXIIProject/libtaxii#243]
Line 696 in messages_11.py calls `etree.tostring(self._content)` and this call may end up in a SerialisationError even for valid XML content (with unicode characters).

If encoding is declared to utf-8 or unicode it works as expected: `etree.tostring(self._content, encoding='unicode')` and also the resulting output file is properly encoded (poll_client tool).

Example on an error (excerpt):

  File "~/.pyenv/versions/3.7.6/lib/python3.7/site-packages/libtaxii/messages_11.py", line 696, in content
    return etree.tostring(self._content)
  File "src/lxml/etree.pyx", line 3435, in lxml.etree.tostring
  File "src/lxml/serializer.pxi", line 139, in lxml.etree._tostring
  File "src/lxml/serializer.pxi", line 199, in lxml.etree._raiseSerialisationError
lxml.etree.SerialisationError: IO_ENCODER

Workaround: A downgrade of lxml from 4.5.0 to 4.4.0 also fixes this issue (Though, poll_client still creates ASCII files)... 

Root cause seems to be reported here: https://bugs.launchpad.net/lxml/+bug/1873306

**Comment by emmanvg** [comment]
@advptr I proposed some changes that address your issue and added `etree.tostring(self._content, encoding='utf-8')` to any code that uses this method.
