### ISSUE TITLE
Rebuild Docs with recent PR Changes

### ISSUE THREAD

**Issue by arcsector** [TAXIIProject/libtaxii#251]
Hello everyone,

Can you please rebuild the docs and push them to RTD with the recent changes I made in PR #249? That PR will have no effect unless they are rebuilt, or unless people build them from scratch.

Thanks!

**Comment by clenk** [comment]
The changes were displayed at https://libtaxii.readthedocs.io/en/latest/index.html (`latest` branch), but `stable` was the default branch. I switched the default to `latest` for now. So you should be able to see them now. :)

**Comment by arcsector** [comment]
Perfect - thank you, much appreciated.
